; Listing generated by Microsoft (R) Optimizing Compiler Version 19.10.25019.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	main
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+41
	DD	imagerel $unwind$main
pdata	ENDS
xdata	SEGMENT
$unwind$main DD	010401H
	DD	02204H
xdata	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
b$ = 0
a$ = 4
c$ = 8
main	PROC
; File c:\users\bf1g14\desktop\hello_world.c
; Line 4
$LN3:
	sub	rsp, 24
; Line 6
	mov	DWORD PTR a$[rsp], 4
; Line 7
	mov	DWORD PTR b$[rsp], 2
; Line 8
	mov	eax, DWORD PTR b$[rsp]
	mov	ecx, DWORD PTR a$[rsp]
	sub	ecx, eax
	mov	eax, ecx
	mov	DWORD PTR c$[rsp], eax
; Line 9
	xor	eax, eax
; Line 10
	add	rsp, 24
	ret	0
main	ENDP
_TEXT	ENDS
END
